require("elephas.plugins.plugins-setup")

require("elephas.core.options")
require("elephas.core.keymaps")
require("elephas.core.colorscheme")

require("elephas.plugins.lualine")
require("elephas.plugins.nvim-tree")
require("elephas.plugins.nvim-cmp")
require("elephas.plugins.lsp.mason")
require("elephas.plugins.lsp.lspsaga")
require("elephas.plugins.lsp.lspconfig")
require("elephas.plugins.lsp.null-ls")
require("elephas.plugins.autopairs")
require("elephas.plugins.treesitter")
require("elephas.plugins.gitsigns")
require("elephas.plugins.fluttertools")
